version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linguapulse-onboarding"
s3_bucket = "linguapulse-lambda-deployments"
s3_prefix = "onboarding"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SupabaseUrl=https://qpqwyvzpwwwyolnvtglw.supabase.co SupabaseAnonKey=sb_publishable_KXoBxRqLGEu15QacTZA0xA_NVYYW7VW TelegramBotToken=8079926642:AAF-sO6ss9l7kby2t3m0iX5TtKJ9HKbxA3Q"
image_repositories = []
