name = "linguapulse-lesson0-bot"
main = "lesson0-bot.js"
compatibility_date = "2025-05-17"
keep_vars = true

[[kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427" 