name = "linguapulse"
compatibility_date = "2025-05-17"

# Global observability settings
[observability.logs]
enabled = true

# Secret Variables (DO NOT ADD THESE TO THIS FILE):
# These should be set using 'wrangler secret put' or Cloudflare Dashboard:
# - TRIBUTE_APP_LINK: Primary link for Tribute app subscription (https://t.me/tribute/app?startapp=stO5)
# - TRIBUTE_CHANNEL_LINK: Backup link for Tribute channel subscription
# - BOT_TOKEN: Telegram bot token
#
# Example: npx wrangler secret put TRIBUTE_APP_LINK --env webhook
# Example: npx wrangler secret put BOT_TOKEN --env webhook

# Test Bot Environment
[env.test-bot]
name = "linguapulse-test-bot"
main = "linguapulse-test-bot.js"

[[env.test-bot.kv_namespaces]]
binding = "TEST_KV" 
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.test-bot.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Webhook Environment  
[env.webhook]
name = "telegram-webhook"
main = "telegram-webhook.js"

[[env.webhook.kv_namespaces]]
binding = "TEST_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.webhook.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Lesson0 Environment
[env.lesson0]
name = "linguapulse-lesson0-bot"
main = "lesson0-bot.js"

[[env.lesson0.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.lesson0.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Main Lesson Environment
[env.main-lesson]
name = "main-lesson"
main = "main-lesson.js"

[[env.main-lesson.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.main-lesson.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Payment Environment
[env.payment]
name = "payment-worker"
main = "payment.js"

[[env.payment.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Reminder Environment
[env.reminder]
name = "reminder"
main = "reminder.js"

[[env.reminder.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"