name = "linguapulse-test-bot"
main = "linguapulse-test-bot.js"
compatibility_date = "2025-05-17"

# Привязки KV и D1 - замените ID на реальные
[kv_namespaces]
TEST_KV = { binding = "TEST_KV", id = "ff3bf4d1633d45cd92e95d193b7d250f" }

[d1_databases]
USER_DB = { binding = "USER_DB", database_id = "47f30572-4b57-4978-890d-4fa880cf1427" }
