name = "linguapulse"
compatibility_date = "2025-05-17"
keep_vars = true

# Global observability settings - Keeping logs enabled across all environments
[observability]
  [observability.logs]
  enabled = true

# Secret Variables (DO NOT ADD THESE TO THIS FILE):
# These should be set using 'wrangler secret put' or Cloudflare Dashboard:
# - TRIBUTE_APP_LINK: Primary link for Tribute app subscription (https://t.me/tribute/app?startapp=stO5)
# - TRIBUTE_CHANNEL_LINK: Backup link for Tribute channel subscription
# - TRIBUTE_API_KEY: API key for verifying Tribute webhooks
# - BOT_TOKEN: Telegram bot token
# - OPENAI_KEY: OpenAI API key
# - TRANSLOADIT_KEY: Transloadit API key 
# - TRANSLOADIT_TPL: Transloadit template ID
#
# Example: npx wrangler secret put TRIBUTE_APP_LINK --env webhook
# Example: npx wrangler secret put BOT_TOKEN --env webhook

# Test Bot Environment
[env.test-bot]
name = "linguapulse-test-bot"
main = "linguapulse-test-bot.js"
keep_vars = true

# Enable logs specifically for this environment
[env.test-bot.observability]
  [env.test-bot.observability.logs]
  enabled = true

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.test-bot.kv_namespaces]]
binding = "TEST_KV" 
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.test-bot.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Webhook Environment  
[env.webhook]
name = "telegram-webhook"
main = "telegram-webhook.js"
keep_vars = true

# Enable logs specifically for this environment
[env.webhook.observability]
  [env.webhook.observability.logs]
  enabled = true

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.webhook.kv_namespaces]]
binding = "TEST_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.webhook.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Сервисные привязки для окружения webhook
[[env.webhook.services]]
binding = "TEST"
service = "linguapulse-test-bot"

[[env.webhook.services]]
binding = "LESSON0"
service = "linguapulse-lesson0-bot"

[[env.webhook.services]]
binding = "MAIN_LESSON"
service = "main-lesson"



# Lesson0 Environment
[env.lesson0]
name = "linguapulse-lesson0-bot"
main = "lesson0-bot.js"
compatibility_date = "2025-05-17"
keep_vars = true

# Enable logs specifically for this environment
[env.lesson0.observability]
  [env.lesson0.observability.logs]
  enabled = true

# Переменные окружения настраиваются через:
# - GitHub Actions при CI/CD
# - wrangler secret put для локальной разработки
# - Cloudflare Dashboard для ручной настройки
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

# ВАЖНО: Не определяйте пустые значения переменных!
# Примеры необходимых переменных (должны быть настроены через secrets/dashboard):
# - BOT_TOKEN: Telegram bot token
# - OPENAI_KEY: OpenAI API key
# - TRANSLOADIT_KEY: Transloadit API key 
# - TRANSLOADIT_TPL: Transloadit template ID
# - SYSTEM_PROMPT: Системный промпт для GPT

[[env.lesson0.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.lesson0.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Main Lesson Environment
[env.main-lesson]
name = "main-lesson"
main = "main-lesson.js"
keep_vars = true

# Enable logs specifically for this environment
[env.main-lesson.observability]
  [env.main-lesson.observability.logs]
  enabled = true

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.main-lesson.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.main-lesson.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"



# Reminder Environment
[env.reminder]
name = "reminder"
main = "reminder.js"
keep_vars = true

# Enable logs specifically for this environment
[env.reminder.observability]
  [env.reminder.observability.logs]
  enabled = true

[[env.reminder.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# ========== DEV ENVIRONMENTS ==========
# These environments are for development and testing
# They use separate resources to avoid affecting production

# Dev Test Bot Environment
[env.dev-test-bot]
name = "dev-linguapulse-test-bot"
main = "linguapulse-test-bot.js"
keep_vars = true

[env.dev-test-bot.observability]
  [env.dev-test-bot.observability.logs]
  enabled = true

[[env.dev-test-bot.kv_namespaces]]
binding = "TEST_KV" 
id = "cc6437f9f5b647a4bf4d8a61fb1d950d"

[[env.dev-test-bot.d1_databases]]
binding = "USER_DB"
database_id = "9eff8ecf-456d-4f6a-adda-e6163deba886"

# Dev Webhook Environment  
[env.dev-webhook]
name = "dev-telegram-webhook"
main = "telegram-webhook.js"
keep_vars = true

[env.dev-webhook.observability]
  [env.dev-webhook.observability.logs]
  enabled = true

[[env.dev-webhook.kv_namespaces]]
binding = "TEST_KV"
id = "cc6437f9f5b647a4bf4d8a61fb1d950d"

[[env.dev-webhook.d1_databases]]
binding = "USER_DB"
database_id = "9eff8ecf-456d-4f6a-adda-e6163deba886"

# Dev service bindings
[[env.dev-webhook.services]]
binding = "TEST"
service = "dev-linguapulse-test-bot"

[[env.dev-webhook.services]]
binding = "LESSON0"
service = "dev-linguapulse-lesson0-bot"

[[env.dev-webhook.services]]
binding = "MAIN_LESSON"
service = "dev-main-lesson"

# Dev Lesson0 Environment
[env.dev-lesson0]
name = "dev-linguapulse-lesson0-bot"
main = "lesson0-bot.js"
compatibility_date = "2025-05-17"
keep_vars = true

[env.dev-lesson0.observability]
  [env.dev-lesson0.observability.logs]
  enabled = true

[[env.dev-lesson0.kv_namespaces]]
binding = "CHAT_KV"
id = "cc6437f9f5b647a4bf4d8a61fb1d950d"

[[env.dev-lesson0.d1_databases]]
binding = "USER_DB"
database_id = "9eff8ecf-456d-4f6a-adda-e6163deba886"

# Dev Main Lesson Environment
[env.dev-main-lesson]
name = "dev-main-lesson"
main = "main-lesson.js"
keep_vars = true

[env.dev-main-lesson.observability]
  [env.dev-main-lesson.observability.logs]
  enabled = true

[[env.dev-main-lesson.kv_namespaces]]
binding = "CHAT_KV"
id = "cc6437f9f5b647a4bf4d8a61fb1d950d"

[[env.dev-main-lesson.d1_databases]]
binding = "USER_DB"
database_id = "9eff8ecf-456d-4f6a-adda-e6163deba886"

# Dev Reminder Environment
[env.dev-reminder]
name = "dev-reminder"
main = "reminder.js"
keep_vars = true

[env.dev-reminder.observability]
  [env.dev-reminder.observability.logs]
  enabled = true

[[env.dev-reminder.d1_databases]]
binding = "USER_DB"
database_id = "9eff8ecf-456d-4f6a-adda-e6163deba886"

# Dev database direct access for management (only for CLI commands)
# Note: This binding is not inherited by environments and is only for wrangler CLI access