name = "linguapulse"
compatibility_date = "2025-05-17"
keep_vars = true

# Global observability settings
[observability.logs]
enabled = true

# Secret Variables (DO NOT ADD THESE TO THIS FILE):
# These should be set using 'wrangler secret put' or Cloudflare Dashboard:
# - TRIBUTE_APP_LINK: Primary link for Tribute app subscription (https://t.me/tribute/app?startapp=stO5)
# - TRIBUTE_CHANNEL_LINK: Backup link for Tribute channel subscription
# - TRIBUTE_API_KEY: API key for verifying Tribute webhooks
# - BOT_TOKEN: Telegram bot token
# - OPENAI_KEY: OpenAI API key
# - TRANSLOADIT_KEY: Transloadit API key 
# - TRANSLOADIT_TPL: Transloadit template ID
#
# Example: npx wrangler secret put TRIBUTE_APP_LINK --env webhook
# Example: npx wrangler secret put BOT_TOKEN --env webhook

# Test Bot Environment
[env.test-bot]
name = "linguapulse-test-bot"
main = "linguapulse-test-bot.js"

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.test-bot.kv_namespaces]]
binding = "TEST_KV" 
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.test-bot.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Webhook Environment  
[env.webhook]
name = "telegram-webhook"
main = "telegram-webhook.js"

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.webhook.kv_namespaces]]
binding = "TEST_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.webhook.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Сервисные привязки для окружения webhook
[[env.webhook.services]]
binding = "TEST"
service = "linguapulse-test-bot"

[[env.webhook.services]]
binding = "LESSON0"
service = "linguapulse-lesson0-bot"

[[env.webhook.services]]
binding = "MAIN_LESSON"
service = "main-lesson"

[[env.webhook.services]]
binding = "PAYMENT"
service = "payment"

# Lesson0 Environment
[env.lesson0]
name = "linguapulse-lesson0-bot"
main = "lesson0-bot.js"
compatibility_date = "2025-05-17"
keep_vars = true

# Переменные окружения настраиваются через:
# - GitHub Actions при CI/CD
# - wrangler secret put для локальной разработки
# - Cloudflare Dashboard для ручной настройки
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

# ВАЖНО: Не определяйте пустые значения переменных!
# Примеры необходимых переменных (должны быть настроены через secrets/dashboard):
# - BOT_TOKEN: Telegram bot token
# - OPENAI_KEY: OpenAI API key
# - TRANSLOADIT_KEY: Transloadit API key 
# - TRANSLOADIT_TPL: Transloadit template ID
# - SYSTEM_PROMPT: Системный промпт для GPT

[[env.lesson0.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.lesson0.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Main Lesson Environment
[env.main-lesson]
name = "main-lesson"
main = "main-lesson.js"

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.main-lesson.kv_namespaces]]
binding = "CHAT_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

[[env.main-lesson.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Payment Environment
[env.payment]
name = "payment"
main = "payment.js"

# Переменные окружения настраиваются через CI/CD или Dashboard
# НЕ ОПРЕДЕЛЯЙТЕ переменные с пустыми значениями, это затирает их значения!

[[env.payment.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

# Reminder Environment
[env.reminder]
name = "reminder"
main = "reminder.js"

[[env.reminder.d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"