name = "linguapulse-test-bot"
main = "linguapulse-test-bot.js"
compatibility_date = "2025-05-17"

# KV namespaces должны быть в формате массива
[[kv_namespaces]]
binding = "TEST_KV"
id = "ff3bf4d1633d45cd92e95d193b7d250f"

# D1 databases также должны быть в формате массива
[[d1_databases]]
binding = "USER_DB"
database_id = "47f30572-4b57-4978-890d-4fa880cf1427"

[build]
command = ""
bundle = false
minify = false

[worker_output]
filename = "worker.js" # Это заменило service_worker_name

# Настройки логирования
[observability.logs]
enabled = true
