name = "telegram-webhook"
main = "telegram-webhook.js"
compatibility_date = "2025-05-17"
keep_vars = true

# Global observability settings
[observability]
  [observability.logs]
  enabled = true

# Secret Variables (set via Cloudflare Dashboard or wrangler secret put):
# - BOT_TOKEN: Telegram bot token
# - ONBOARDING_URL: AWS Lambda Function URL for onboarding
# - AWS_LAMBDA_TOKEN: Token for Lambda authentication
# Updated: 2025-01-09 - CI/CD workflow fixed

[env.webhook]