name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей основной ветки
  workflow_dispatch:  # позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      # Деплой только telegram-webhook для тестирования Lambda интеграции
      - name: Deploy telegram-webhook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env webhook --keep-vars