name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'Cloudflare Worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(toJSON(github.event.head_commit.modified), 'Cloudflare Worker/') || contains(toJSON(github.event.head_commit.added), 'Cloudflare Worker/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'Cloudflare Worker'