name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей основной ветки
  workflow_dispatch:  # позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install

      # Деплой всех воркеров
      - name: Deploy telegram-webhook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: webhook
          
      - name: Deploy test-bot
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: test-bot
          
      - name: Deploy main-lesson
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: main-lesson
          
      - name: Deploy payment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: payment
          
      - name: Deploy reminder
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: reminder

      # Отдельный деплой для lesson0-bot с корректной установкой Transloadit
      - name: Deploy lesson0-bot with secrets
        run: |
          # Проверка конфигурации
          echo "Проверка конфигурации wrangler.toml для lesson0-bot..."
          if ! grep -q "TRANSLOADIT_KEY" wrangler.toml; then
            echo "ОШИБКА: TRANSLOADIT_KEY не определен в wrangler.toml"
            exit 1
          fi
          
          # Создание файла с переменными окружения
          echo "Создание файла с переменными окружения..."
          cat > .dev.vars <<EOF
          TRANSLOADIT_KEY="${{ secrets.TRANSLOADIT_KEY }}"
          TRANSLOADIT_TPL="${{ secrets.TRANSLOADIT_TPL }}"
          OPENAI_KEY="${{ secrets.OPENAI_KEY }}"
          BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          SYSTEM_PROMPT="${{ secrets.SYSTEM_PROMPT }}"
          EOF
          
          # Деплой с использованием файла переменных
          echo "Деплой lesson0-bot с переменными из файла..."
          npx wrangler deploy lesson0-bot.js --env lesson0 --var-file=.dev.vars
          
          # Установка секретов через wrangler для гарантии
          echo "Установка секретов через wrangler CLI..."
          echo "${{ secrets.TRANSLOADIT_KEY }}" | npx wrangler secret put TRANSLOADIT_KEY --env lesson0
          echo "${{ secrets.TRANSLOADIT_TPL }}" | npx wrangler secret put TRANSLOADIT_TPL --env lesson0
          echo "${{ secrets.OPENAI_KEY }}" | npx wrangler secret put OPENAI_KEY --env lesson0
          echo "${{ secrets.BOT_TOKEN }}" | npx wrangler secret put BOT_TOKEN --env lesson0
          
          # Проверка переменных
          echo "Деплой завершен, переменные должны быть установлены" 