name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей основной ветки
  workflow_dispatch:  # позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      # Деплой всех воркеров через стандартные действия с сохранением переменных
      - name: Deploy telegram-webhook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env webhook --keep-vars
          
      - name: Deploy test-bot
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env test-bot --keep-vars
          
      - name: Deploy main-lesson
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env main-lesson --keep-vars
          

          
      - name: Deploy reminder
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --env reminder --keep-vars
          
      # Специальный шаг для установки переменных и деплоя lesson0-bot
      - name: Setup and deploy lesson0-bot
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "Настройка и деплой lesson0-bot..."
          
          # Проверка настройки переменных
          echo "Проверка текущих переменных..."
          npx wrangler secret list --env lesson0
          
          # Создаем временный файл wrangler-temp.toml с переменными
          cat > wrangler-temp.toml << EOF
          name = "linguapulse-lesson0-bot"
          main = "lesson0-bot.js"
          compatibility_date = "2025-05-17"
          keep_vars = true
          
          [[kv_namespaces]]
          binding = "CHAT_KV"
          id = "ff3bf4d1633d45cd92e95d193b7d250f"
          
          [[d1_databases]]
          binding = "USER_DB"
          database_id = "47f30572-4b57-4978-890d-4fa880cf1427"
          EOF
          
          # Деплой с временным файлом конфигурации
          echo "Деплой lesson0-bot с явными переменными..."
          npx wrangler deploy --config wrangler-temp.toml --keep-vars
          
          # Проверяем наличие секретов перед установкой
          SECRETS=$(npx wrangler secret list --env lesson0)
          
          if ! echo "$SECRETS" | grep -q "BOT_TOKEN"; then
            echo "Устанавливаем BOT_TOKEN..."
            echo "${{ secrets.BOT_TOKEN }}" | npx wrangler secret put BOT_TOKEN --env lesson0
          fi
          
          if ! echo "$SECRETS" | grep -q "OPENAI_KEY"; then
            echo "Устанавливаем OPENAI_KEY..."
            echo "${{ secrets.OPENAI_KEY }}" | npx wrangler secret put OPENAI_KEY --env lesson0
          fi
          
          if ! echo "$SECRETS" | grep -q "TRANSLOADIT_KEY"; then
            echo "Устанавливаем TRANSLOADIT_KEY..."
            echo "${{ secrets.TRANSLOADIT_KEY }}" | npx wrangler secret put TRANSLOADIT_KEY --env lesson0
          fi
          
          if ! echo "$SECRETS" | grep -q "TRANSLOADIT_TPL"; then
            echo "Устанавливаем TRANSLOADIT_TPL..."
            echo "${{ secrets.TRANSLOADIT_TPL }}" | npx wrangler secret put TRANSLOADIT_TPL --env lesson0 || echo "TRANSLOADIT_TPL уже существует, пропускаем"
          fi
          
          # Для SYSTEM_PROMPT пропускаем установку, т.к. он уже существует
          # if ! echo "$SECRETS" | grep -q "SYSTEM_PROMPT"; then
          #  echo "Устанавливаем SYSTEM_PROMPT..."
          #  echo "${{ secrets.SYSTEM_PROMPT }}" | npx wrangler secret put SYSTEM_PROMPT --env lesson0
          # fi
          
          # Проверка настройки после деплоя
          echo "Проверка переменных после настройки..."
          npx wrangler secret list --env lesson0

      # CRITICAL FIX: Setup main-lesson worker secrets (missing in production!)
      - name: Setup main-lesson worker secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "Setting up main-lesson worker secrets..."
          
          # Check existing secrets
          echo "Checking current secrets for main-lesson..."
          SECRETS=$(npx wrangler secret list --env main-lesson)
          
          if ! echo "$SECRETS" | grep -q "BOT_TOKEN"; then
            echo "Setting BOT_TOKEN for main-lesson..."
            echo "${{ secrets.BOT_TOKEN }}" | npx wrangler secret put BOT_TOKEN --env main-lesson
          else
            echo "BOT_TOKEN already exists for main-lesson, skipping"
          fi
          
          if ! echo "$SECRETS" | grep -q "OPENAI_KEY"; then
            echo "Setting OPENAI_KEY for main-lesson..."
            echo "${{ secrets.OPENAI_KEY }}" | npx wrangler secret put OPENAI_KEY --env main-lesson
          else
            echo "OPENAI_KEY already exists for main-lesson, skipping"
          fi
          
          if ! echo "$SECRETS" | grep -q "TRANSLOADIT_KEY"; then
            echo "Setting TRANSLOADIT_KEY for main-lesson..."
            echo "${{ secrets.TRANSLOADIT_KEY }}" | npx wrangler secret put TRANSLOADIT_KEY --env main-lesson
          else
            echo "TRANSLOADIT_KEY already exists for main-lesson, skipping"
          fi
          
          if ! echo "$SECRETS" | grep -q "TRANSLOADIT_TPL"; then
            echo "Setting TRANSLOADIT_TPL for main-lesson..."
            echo "${{ secrets.TRANSLOADIT_TPL }}" | npx wrangler secret put TRANSLOADIT_TPL --env main-lesson
          else
            echo "TRANSLOADIT_TPL already exists for main-lesson, skipping"
          fi
          
          # Check setup after deployment
          echo "Verifying main-lesson secrets after setup..."
          npx wrangler secret list --env main-lesson

      # Setup telegram-webhook worker secrets  
      - name: Setup telegram-webhook worker secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "Setting up telegram-webhook worker secrets..."
          
          # Check existing secrets
          echo "Checking current secrets for telegram-webhook..."
          SECRETS=$(npx wrangler secret list --env webhook)
          
          if ! echo "$SECRETS" | grep -q "BOT_TOKEN"; then
            echo "Setting BOT_TOKEN for telegram-webhook..."
            echo "${{ secrets.BOT_TOKEN }}" | npx wrangler secret put BOT_TOKEN --env webhook
          else
            echo "BOT_TOKEN already exists for telegram-webhook, skipping"
          fi
          
          if ! echo "$SECRETS" | grep -q "TRIBUTE_API_KEY"; then
            echo "Setting TRIBUTE_API_KEY for telegram-webhook..."
            echo "${{ secrets.TRIBUTE_API_KEY }}" | npx wrangler secret put TRIBUTE_API_KEY --env webhook
          else
            echo "TRIBUTE_API_KEY already exists for telegram-webhook, skipping"
          fi
          
          # Check setup after deployment
          echo "Verifying telegram-webhook secrets after setup..."
          npx wrangler secret list --env webhook

      # Информация о переменных для других воркеров
      - name: Note about other workers variables
        run: |
          echo "⚠️ ВАЖНО: Переменные для других воркеров должны быть настроены через Cloudflare Dashboard."
          echo "Для настройки переменных вручную используйте раздел Settings > Variables and Secrets в Dashboard."
          echo "API-метод для настройки переменных не работает с текущим токеном."

      # Информация о переменных
      - name: Note about variables
        run: |
          echo "✅ Все воркеры теперь деплоятся с флагом --keep-vars"
          echo "✅ Это сохраняет существующие переменные при деплое"
          echo "✅ Вам нужно настроить переменные только один раз через Dashboard" 